name: Deploy to Customer (Manual)

on:
  workflow_dispatch:
    inputs:
      customer:
        required: true
        type: choice
        description: Select customer to deploy
        default: "Apple"
        options:
          - "Apple"
          - "Tesla"
          - "Test"

jobs:
  token-thing:
    environment: ${{ github.event.inputs.customer }}
    runs-on: ubuntu-latest
    steps:
        - name: Check if TOKEN is empty
          run: |
            if [ -z "${TOKEN}" ]; then
            echo "TOKEN is empty or not set"
            else
            echo "TOKEN is set"
            echo "Token Length: ${#TOKEN}"
            fi
          env:
            TOKEN: ${{ secrets.AZURE_TOKEN }}
  call-workflow-passing-data-apple:
    if: ${{ github.event.inputs.customer == 'Apple' }}
    uses: ./.github/workflows/deploy.yml
    with:
      SITE_NAME: "apple location 1"
      ACCOUNT: "account 1"
      RESOURCE_GROUP: "azure-rg-1"
    secrets:
      TOKEN: ${{ secrets.AZURE_TOKEN }}

  call-workflow-passing-data-tesla:
    if: ${{ github.event.inputs.customer == 'Tesla' }}
    uses: ./.github/workflows/deploy.yml
    with:
      SITE_NAME: "tesla location 1"
      ACCOUNT: "account 1"
      RESOURCE_GROUP: "azure-rg-1"
    secrets:
      TOKEN: ${{ secrets.AZURE_TOKEN }}

  call-workflow-passing-data-test:
    if: ${{ github.event.inputs.customer == 'Test' }}
    uses: ./.github/workflows/deploy.yml
    with:
      SITE_NAME: "test location 1"
      ACCOUNT: "account 1"
      RESOURCE_GROUP: "azure-rg-1"
    secrets:
      TOKEN: ${{ secrets.AZURE_TOKEN }}

