name: Deploy to Customer (Manual)

on:
  workflow_dispatch:
    inputs:
      customer:
        required: true
        type: choice
        description: Select customer to deploy
        default: "Test"
        options:
          - "Apple"
          - "Tesla"
          - "Test"

jobs:
  echo-customer:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.customer }}
    steps:
      - name: Echo customer and environment variable
        env:
          ENV_VAR: ${{ secrets.SECRET_DESCRIPTION }}
        run: |
          echo "Customer: ${{ github.event.inputs.customer }}"
          echo "Environment Variable: $ENV_VAR"

